Cách gán giá trị cho biến trong Python

In [1]:
mass = 47.5
age = 122

mass = mass * 2.0
age = age - 20

print('giá trị hiện tại của mass là:', mass)
print('giá trị hiện tại của age là:', age)

giá trị hiện tại của mass là: 95.0
giá trị hiện tại của age là: 102


Arrays can be concatenated and stacked on top of one another, using NumPy’s vstack and hstack functions for vertical and horizontal stacking, respectively.

In [5]:
import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


Hàm Loop

In [6]:
result=1
for i in range(0,3):
    result=result*5
print(result)

125


In [8]:
print(5**3)

125


Storing mutiple values in lists

Just as a for loop is a way to do operations many times, a list is a way to store many values. Unlike NumPy arrays, lists are built into the language (so we don’t have to load a library to use them). We create a list by putting values inside square brackets and separating the values with commas:

In [9]:
odds = [1, 3, 5, 7]
print('odds are:', odds)

odds are: [1, 3, 5, 7]


In [10]:
type(odds)

list

We select individual elements from lists by indexing them:

In [11]:
print('first and last:', odds[0], odds[-1])

first and last: 1 7


and if we loop over a list, the loop variable is assigned elements one at a time:

In [12]:
for x in odds:
    print(x)

1
3
5
7


There is one important difference between lists and strings: we can change the values in a list, but we cannot change individual characters in a string. For example:

In [13]:
names = ['Newton', 'Darwing', 'Turing'] # typo in Darwin's name
print('names is originally:', names)
names[1] = 'Darwin' # correct the name
print('final value of names:', names)

names is originally: ['Newton', 'Darwing', 'Turing']
final value of names: ['Newton', 'Darwin', 'Turing']


works, but:

In [14]:
name = 'Darwin'
name[0] = 'd'

TypeError: 'str' object does not support item assignment

# Ch-Ch-Ch-Changes

Data which can be modified in place is called mutable, while data which cannot be modified is called immutable. Strings and numbers are immutable. This does not mean that variables with string or number values are constants, but when we want to change the value of a string or number variable, we can only replace the old value with a completely new value.

Lists and arrays, on the other hand, are mutable: we can modify them after they have been created. We can change individual elements, append new elements, or reorder the whole list. For some operations, like sorting, we can choose whether to use a function that modifies the data in place or a function that returns a modified copy and leaves the original unchanged.

Be careful when modifying data in place. If two variables refer to the same list, and you modify the list value, it will change for both variables! If you want variables with mutable values to be independent, you must make a copy of the value when you assign it.

Because of pitfalls like this, code which modifies data in place can be more difficult to understand. However, it is often far more efficient to modify a large data structure in place than to create a modified copy for every small change. You should consider both of these aspects when writing your code.

# Nested Lists

Since lists can contain any Python variable, it can even contain other lists.

For example, we could represent the products in the shelves of a small grocery shop:

In [15]:
x = [['pepper', 'zucchini', 'onion'],
     ['cabbage', 'lettuce', 'garlic'],
     ['apple', 'pear', 'banana']]

Here is a visual example of how indexing a list of lists x works:

In [16]:
print(x[0])

['pepper', 'zucchini', 'onion']


In [17]:
print(x[0][0])

pepper


There are many ways to change the contents of lists besides assigning new values to individual elements:

In [20]:
odds.append(20)
print('odds after adding a value:', odds)

odds after adding a value: [1, 3, 5, 7, 11, 19, 20]


In [21]:
del odds[0]
print('odds after removing the first element:', odds)

odds after removing the first element: [3, 5, 7, 11, 19, 20]


In [22]:
odds.reverse()
print('odds after reversing:', odds)

odds after reversing: [20, 19, 11, 7, 5, 3]


While modifying in place, it is useful to remember that Python treats lists in a slightly counter-intuitive way.

If we make a list and (attempt to) copy it then modify in place, we can cause all sorts of trouble:

In [23]:
odds = [1, 3, 5, 7]
primes = odds
primes += [2]
print('primes:', primes)
print('odds:', odds)

primes: [1, 3, 5, 7, 2]
odds: [1, 3, 5, 7, 2]


This is because Python stores a list in memory, and then can use multiple names to refer to the same list. If all we want to do is copy a (simple) list, we can use the list function, so we do not modify a list we did not mean to:

In [24]:
odds = [1, 3, 5, 7]
primes = list(odds)
primes += [2]
print('primes:', primes)
print('odds:', odds)

primes: [1, 3, 5, 7, 2]
odds: [1, 3, 5, 7]


# Slicing list/string

In [27]:
binomial_name = "Drosophila melanogaster"
group = binomial_name[0:10]
print("group:", group)

species = binomial_name[11:24]
print("species:", species)

chromosomes = ["X", "Y", "2", "3", "4"]
autosomes = chromosomes[2:5]
print("autosomes:", autosomes)

last = chromosomes[-1]
print("last:", last)

group: Drosophila
species: melanogaster
autosomes: ['2', '3', '4']
last: 4


In [29]:
string_for_slicing = "Observation date: 02-Feb-2013"
list_for_slicing = [["fluorine", "F"], ["chlorine", "Cl"], ["bromine", "Br"], ["iodine", "I"], ["astatine", "At"]]

print(string_for_slicing[-4:])
print(list_for_slicing[-4:])

2013
[['chlorine', 'Cl'], ['bromine', 'Br'], ['iodine', 'I'], ['astatine', 'At']]


In [30]:
date = "Monday 4 January 2016"
day = date[0:6]
print("Using 0 to begin range:", day)
day = date[:6]
print("Omitting beginning index:", day)

Using 0 to begin range: Monday
Omitting beginning index: Monday


In [31]:
months = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]
sond = months[8:12]
print("With known last position:", sond)
sond = months[8:len(months)]
print("Using len() to get last entry:", sond)
sond = months[8:]
("Omitting ending index:", sond)

With known last position: ['sep', 'oct', 'nov', 'dec']
Using len() to get last entry: ['sep', 'oct', 'nov', 'dec']


('Omitting ending index:', ['sep', 'oct', 'nov', 'dec'])

# Tuples and Exchanges

In [34]:
left = 'L'
right = 'R'

temp = left
left = right
right = temp

print(left,right)
print(temp)

R L
L


In [33]:
left = 'L'
right = 'R'

left='R'
right=left

print(left,right)

R R


# Overloading

In [35]:
counts = [2, 4, 6, 8, 10]
repeats = counts * 2
print(repeats)

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]


In [37]:
counts = [2, 4, 6, 8, 10]
repeats = counts + counts
print(repeats)

[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]


Hàm if kết hợp với for

In [38]:
positive_sum = 0
negative_sum = 0
test_list = [3, 4, 6, 1, -1, -5, 0, 7, -8]
for num in test_list:
    if num > 0:
        positive_sum += num
    elif num == 0:
        pass
    else:
        negative_sum += num
print(positive_sum, negative_sum)

21 -14


Sử dụng hàm if để chia các file thành nhiều nhóm. Cách khác là dùng hàm glob.glob trong phần "Làm việc với nhiều file dữ liệu"

In [39]:
files = ['inflammation-01.csv', 'myscript.py', 'inflammation-02.csv', 'small-01.csv', 'small-02.csv']
large_files = []
small_files = []
other_files = []

for file in files:
    if 'inflammation-' in file:
        large_files.append(file)
    elif 'small-' in file:
        small_files.append(file)
    else:
        other_files.append(file)
        
print(large_files)
print(small_files)
print(other_files)

['inflammation-01.csv', 'inflammation-02.csv']
['small-01.csv', 'small-02.csv']
['myscript.py']


Sự khác nhau giữa Python2 và 3: 
Trong Python2:5/9=0 (tự động làm tròn); float(5)/9=0.55555555556

Nhưng trong Python3:

In [40]:
5/9

0.5555555555555556

In [41]:
5//9

0

Sự khác nhau giữa list và array

In [42]:
a=[1,2,3,4,5]
b=numpy.array([1,2,3,4,5],float)

type(a),type(b)

(list, numpy.ndarray)

In [43]:
c=a*2
print(c)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [45]:
d=b*2
print(d)

[  2.   4.   6.   8.  10.]


In [48]:
#e=a**2
f=b**2
#print(e)
print(f)

[  1.   4.   9.  16.  25.]
